Limit "all" option to Mac.
Adding 100s of UUIDs to the scan filter on BlueZ causes BlueZ to fail
with:

    Traceback (most recent call last):
    File "examples/detection_callback.py", line 53, in <module>
        asyncio.run(main(service_uuids))
    File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
        return loop.run_until_complete(main)
    File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
        return future.result()
    File "examples/detection_callback.py", line 42, in main
        await scanner.start()
    File "/home/david/work/pybricks/bleak/bleak/backends/bluezdbus/scanner.py", line 169, in start
        assert_reply(reply)
    File "/home/david/work/pybricks/bleak/bleak/backends/bluezdbus/utils.py", line 23, in assert_reply
        raise BleakDBusError(reply.error_name, reply.body)
    bleak.exc.BleakDBusError: [org.bluez.Error.InProgress] Operation already in progress

`bluetoothd` has to be restarted to clear the error.

So don't allow this option on OS other than Mac. Also drop the "all"
option and enable it by default based on the macOS version.

Fixes: https://github.com/hbldh/bleak/issues/716