Add error description to BleakDBusError in addition to error name
Converting BleakDBusError to string now adds detailed description of the
error, which can be very useful for debugging, as more than 12 different
errors are reported under org.bluez.Error.Failed error name.

Instead of
  bleak.exc.BleakDBusError: org.bluez.Error.Failed
one now gets
  bleak.exc.BleakDBusError: org.bluez.Error.Failed (Operation failed
  with ATT error: 0x0e = Connection Rejected Due To Security Reasons)

Some details are less useful, as example
  bleak.exc.BleakDBusError: org.bluez.Error.AuthenticationFailed
becomes
  bleak.exc.BleakDBusError: org.bluez.Error.AuthenticationFailed
  (Authentication Failed)

But looking at more possible error codes and their details (majority
from BlueZ sources gdbus/object.c and src/gatt-client.c), it becomes
clear that additional description of error can be very useful:
  org.freedesktop.DBus.Error.InvalidArgs
  org.freedesktop.DBus.Error.UnknownProperty
    No such interface '%s'
    No such property '%s'
    Invalid signature for '%s'
    Invalid argument type: '%c'
    Property '%s' is not readable
    Property '%s' is not writable
    No arguments given
  org.bluez.Error.Failed
    `strerror(-err)`
    Connect failed
    Not connected
    Invalid UUID
    Operation failed with ATT error: 0x%02x
    Failed to initiate write
    ... and many more

Signed-off-by: Bojan Potočnik <info@bojanpotocnik.com>