backends/bluezdbus/client: fix raising BleakDeviceNotFoundError in connect
The comparison of reply.error_name to the ErrorType enum was incorrect
since the former is a string value. So we were still getting the old
error:

    bleak.exc.BleakDBusError: [org.freedesktop.DBus.Error.UnknownObject] Method "Connect" with signature "" on interface "org.bluez.Device1" doesn't exist

This fixes the comparison so no we get the expected error.

    bleak.exc.BleakDeviceNotFoundError: Device with address CC:FC:F0:21:7F:3A was not found.