Fix `get_services()`  fails because no GattSession
Since the following error occurred when connecting, set the MTU to the default 20 to avoid it.
`AttributeError: 'NoneType' object has no attribute 'max_pdu_size'`