tests: Fix mypy error
This fixes the following mypy error, which previously only occurred locally and not in CI. However, due to the switch to uv in CI, it now also occurs there. It is unclear why this did not occur in CI before.

error: Cannot determine type of "open_transport_with_bluez_vhci"  [has-type]