corebluetooth: fix crash on disconnect
Fixes the following exception:

    Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
        self._context.run(self._callback, *self._args)
    File "/Users/david/work/bleak/bleak/backends/corebluetooth/CentralManagerDelegate.py", line 358, in did_disconnect_peripheral
        callback()
    File "/Users/david/work/bleak/bleak/backends/corebluetooth/client.py", line 105, in disconnect_callback
        for future in self._delegate.futures():
    File "/Users/david/work/bleak/bleak/backends/corebluetooth/PeripheralDelegate.py", line 77, in futures
        if self._services_discovered_future
    AttributeError: 'PeripheralDelegate' object has no attribute '_services_discovered_future'

Problem was introduced by commit ad59f6e8e35cbab8276d654faafa7856c1fd8b9b.